updates to Git helper scripts

diff --git a/dev_utils/git/git-acp b/dev_utils/git/git-acp
--- a/dev_utils/git/git-acp
+++ b/dev_utils/git/git-acp
@@ -1,12 +1,18 @@
 #!/bin/bash
 #
 # Useful for simple projects looking to add->commit->push in one step
+#
+
+if [ -z "$1" ]; then
+  echo -e "\033[1;31mError:\033[0m Pass a commit message"
+  exit 1
+fi
 
 if [ $(git rev-parse --is-inside-work-tree 2> /dev/null) ]; then
   git_root="$(git rev-parse --show-toplevel)"
   pushd ${git_root} > /dev/null
   git add -A
-  git commit -s
+  git commit -m "$1"
   git push
   popd > /dev/null
 fi
